# Generated by Django 3.2.9 on 2021-12-08 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_orders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='orders',
        ),
    ]
