# Generated by Django 3.2.9 on 2021-12-07 16:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='pid',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
