# Generated by Django 3.2.9 on 2021-12-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0004_delete_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.CharField(max_length=250)),
                ('to', models.CharField(max_length=250)),
                ('data', models.CharField(max_length=50)),
                ('pid', models.IntegerField()),
            ],
        ),
    ]
