# Generated by Django 3.2.9 on 2021-12-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0005_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='products',
            name='image5',
        ),
        migrations.AddField(
            model_name='owners',
            name='phone',
            field=models.IntegerField(default=2.0),
            preserve_default=False,
        ),
    ]
