# Generated by Django 3.2.9 on 2021-12-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('address', models.CharField(max_length=25000)),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=250)),
            ],
        ),
    ]
